### ISSUE TITLE
[question] Usage of tfplugindocs tool to auto-generate documentation

### ISSUE THREAD

**Issue by maxim-nazarenko** [ddelnano/terraform-provider-mikrotik#80]
@ddelnano is it feasable to use [tfplugindocs](github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs) to generate provider docs?

As per [this guide](https://www.terraform.io/registry/providers/docs) the tool can be used if provider contains all the necessary files and correct folders structure.

I am wondering if decision to manually write docs was taken for some reason.

**Comment by ddelnano** [comment]
@maxim-nazarenko that seems like a much better way to manage things :). I think I modeled the repo off another terraform provider that must have existed before `tfplugindocs`. I'm not attached to how we currently do things, so using `tfplugindocs` moving forward sounds great to me.

**Comment by maxim-nazarenko** [comment]
@ddelnano I haven't found any contribution guide for this repo so I'm going to ask in this issue.

What is the best way to update a large amount of resources scattered around in repo:
1. Create on big PR (not the best idea to me as contributor and to you as maintainer ;) )
2. The same as 1 + task list per-resource
3. Create different issues for each activity/resource, e.g.: issue+PR for `resource_dhcp_server`, issue+PR for `resource_dns_record`, issue+PR for introducing `tfplugindocs` into CI.

Option # 3 looks better to me because of granularity and better progress overview.

WDYT? Maybe you have option 4 in mind...

**Comment by ddelnano** [comment]
Option 3 is appealing, but the overhead of creating an issue for each resource sounds too high.

What about having 1 GitHub issue for tracking the migration to `tfplugindocs`, but the initial comment on the issue has a checklist of all the resources that need to be migrated and it links to the relevant PR as they are implemented?

Here's an example of what I'm thinking

tfplugindocs Migration
- [ ] `resource_dhcp_server` (not started yet)
- [x] `resource_dhcp_network` -- #XXX (completed in PR XXX)
- [ ] `resource_dhcp_network` -- #YYY (PR YYY open, but not merged yet)

Since this project doesn't have many contributors, I don't think we need a heavyweight process so I'm open to whatever you want to try.

**Comment by maxim-nazarenko** [comment]
I like your suggestion - it looks clearer.
